name: Build
'on':
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Move Pom.xml to Root
        run: mv .github/workflows/pom.xml ./pom.xml
      - name: Build and analyze
        env:
          GITHUB_TOKEN: >-
            e2035e88-ac6e-40f0-aa7b-2b766a1dd223-6fceb1e7-8f93-4d23-b601-e877d51c0743
          SONAR_TOKEN: 9d7592a215aa5d6c220de85460da10eef432ae2f
        run: >-
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=neojarvis-testing_e2035e88-ac6e-40f0-aa7b-2b766a1dd223-6fceb1e7-8f93-4d23-b601-e877d51c0743
          -Dsonar.login=9d7592a215aa5d6c220de85460da10eef432ae2f
      - name: Trigger API
        if: always()
        env:
          API_URL: '${{ secrets.API_URL }}'
          API_SECRET: '${{ secrets.API_SECRET }}'
        run: >
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2)

          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          API_PAYLOAD="{ \"repo_id\": \"$REPO_NAME\", \"branch_name\":
          \"$BRANCH_NAME\", \"api_secret\": \"$API_SECRET\" }"

          curl -X POST -H "Content-Type: application/json" -d "$API_PAYLOAD"
          $API_URL
